services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    mem_limit: 128m
    environment:
      DOMAIN: "https://vault.house-of-trae.com"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "true"
      ADMIN_TOKEN_FILE: /run/secrets/admin_token
      LOG_LEVEL: "warn"
      SMTP_HOST: "mail.house-of-trae.com"
      SMTP_PORT: "587"
      SMTP_SECURITY: "starttls"
      SMTP_FROM: "notifications@house-of-trae.com"
      SMTP_FROM_NAME: "Vaultwarden"
      SMTP_USERNAME: "notifications@house-of-trae.com"
      SMTP_PASSWORD_FILE: /run/secrets/smtp_password
    secrets:
      - admin_token
      - smtp_password
    volumes:
      - vaultwarden_data:/data
    networks:
      - hotinfra_edge

secrets:
  admin_token:
    file: ./secrets/admin_token.txt
  smtp_password:
    file: ./secrets/smtp_password.txt

volumes:
  vaultwarden_data:

networks:
  hotinfra_edge:
    external: true
