secrets:
  kc_client_secret:
    file: ./secrets/kc_client_secret
  session_secret:
    file: ./secrets/session_secret

services:
  stratus-digital:
    build: ./app
    container_name: stratus-digital
    restart: always
    secrets:
      - kc_client_secret
      - session_secret
    ports:
      - "10.10.30.102:8001:3000"
