services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    secrets:
      - pdns_api_key
      - crowdsec_api_key
    environment:
      PDNS_API_KEY_FILE: /run/secrets/pdns_api_key
    entrypoint: ["/bin/sh", "/etc/caddy/entrypoint.sh"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./entrypoint.sh:/etc/caddy/entrypoint.sh:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:443:443/udp
    networks:
      - edge
secrets:
  pdns_api_key:
    file: ./secrets/pdns_api_key.txt
  crowdsec_api_key:
    file: ./secrets/crowdsec_api_key.txt
volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
networks:
  edge:
    external: true
