services:
  runner:
    image: code.forgejo.org/forgejo/runner:6.3.1
    container_name: forgejo-runner
    group_add:
      - "988"
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      - FORGEJO_INSTANCE_URL=https://git.securenexus.net
      - FORGEJO_RUNNER_NAME=sn-security-runner
      - FORGEJO_RUNNER_LABELS=docker:docker://node:20-bookworm,ubuntu-latest:docker://node:20-bookworm
    volumes:
      - ./data:/data
      - ./config.yaml:/etc/forgejo-runner/config.yaml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - forgejo_runner_token
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  forgejo_runner_token:
    file: ./secrets/forgejo_runner_token
